/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AuthChangePasswordRouteImport } from './routes/_auth/change-password'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminRolesIndexRouteImport } from './routes/_admin/roles/index'
import { Route as AdminPermissionsIndexRouteImport } from './routes/_admin/permissions/index'
import { Route as AdminEventsIndexRouteImport } from './routes/_admin/events/index'
import { Route as AdminEventsNewRouteImport } from './routes/_admin/events/new'
import { Route as AdminUsersProfileIndexRouteImport } from './routes/_admin/users/profile/index'
import { Route as AdminEventsEventIdIndexRouteImport } from './routes/_admin/events/$eventId/index'
import { Route as AdminRolesRoleIdPermissionsRouteImport } from './routes/_admin/roles/$roleId/permissions'
import { Route as AdminEventsEventIdEditRouteImport } from './routes/_admin/events/$eventId/edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsIndexRoute = AdminPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersProfileIndexRoute = AdminUsersProfileIndexRouteImport.update({
  id: '/users/profile/',
  path: '/users/profile/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdIndexRoute = AdminEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoleIdPermissionsRoute =
  AdminRolesRoleIdPermissionsRouteImport.update({
    id: '/roles/$roleId/permissions',
    path: '/roles/$roleId/permissions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventsEventIdEditRoute = AdminEventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/events/new': typeof AdminEventsNewRoute
  '/events/': typeof AdminEventsIndexRoute
  '/permissions/': typeof AdminPermissionsIndexRoute
  '/roles/': typeof AdminRolesIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/events/$eventId/edit': typeof AdminEventsEventIdEditRoute
  '/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
  '/events/$eventId/': typeof AdminEventsEventIdIndexRoute
  '/users/profile/': typeof AdminUsersProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/events/new': typeof AdminEventsNewRoute
  '/events': typeof AdminEventsIndexRoute
  '/permissions': typeof AdminPermissionsIndexRoute
  '/roles': typeof AdminRolesIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/events/$eventId/edit': typeof AdminEventsEventIdEditRoute
  '/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
  '/events/$eventId': typeof AdminEventsEventIdIndexRoute
  '/users/profile': typeof AdminUsersProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/events/new': typeof AdminEventsNewRoute
  '/_admin/events/': typeof AdminEventsIndexRoute
  '/_admin/permissions/': typeof AdminPermissionsIndexRoute
  '/_admin/roles/': typeof AdminRolesIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_admin/events/$eventId/edit': typeof AdminEventsEventIdEditRoute
  '/_admin/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
  '/_admin/events/$eventId/': typeof AdminEventsEventIdIndexRoute
  '/_admin/users/profile/': typeof AdminUsersProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/change-password'
    | '/events/new'
    | '/events/'
    | '/permissions/'
    | '/roles/'
    | '/users/'
    | '/events/$eventId/edit'
    | '/roles/$roleId/permissions'
    | '/events/$eventId/'
    | '/users/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/change-password'
    | '/events/new'
    | '/events'
    | '/permissions'
    | '/roles'
    | '/users'
    | '/events/$eventId/edit'
    | '/roles/$roleId/permissions'
    | '/events/$eventId'
    | '/users/profile'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/login'
    | '/unauthorized'
    | '/_auth/change-password'
    | '/_admin/'
    | '/_admin/events/new'
    | '/_admin/events/'
    | '/_admin/permissions/'
    | '/_admin/roles/'
    | '/_admin/users/'
    | '/_admin/events/$eventId/edit'
    | '/_admin/roles/$roleId/permissions'
    | '/_admin/events/$eventId/'
    | '/_admin/users/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/': {
      id: '/_admin/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/permissions/': {
      id: '/_admin/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AdminPermissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events/': {
      id: '/_admin/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events/new': {
      id: '/_admin/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/profile/': {
      id: '/_admin/users/profile/'
      path: '/users/profile'
      fullPath: '/users/profile/'
      preLoaderRoute: typeof AdminUsersProfileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events/$eventId/': {
      id: '/_admin/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AdminEventsEventIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/$roleId/permissions': {
      id: '/_admin/roles/$roleId/permissions'
      path: '/roles/$roleId/permissions'
      fullPath: '/roles/$roleId/permissions'
      preLoaderRoute: typeof AdminRolesRoleIdPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events/$eventId/edit': {
      id: '/_admin/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AdminEventsEventIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminPermissionsIndexRoute: typeof AdminPermissionsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminEventsEventIdEditRoute: typeof AdminEventsEventIdEditRoute
  AdminRolesRoleIdPermissionsRoute: typeof AdminRolesRoleIdPermissionsRoute
  AdminEventsEventIdIndexRoute: typeof AdminEventsEventIdIndexRoute
  AdminUsersProfileIndexRoute: typeof AdminUsersProfileIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminPermissionsIndexRoute: AdminPermissionsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminEventsEventIdEditRoute: AdminEventsEventIdEditRoute,
  AdminRolesRoleIdPermissionsRoute: AdminRolesRoleIdPermissionsRoute,
  AdminEventsEventIdIndexRoute: AdminEventsEventIdIndexRoute,
  AdminUsersProfileIndexRoute: AdminUsersProfileIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
