/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthChangePasswordRouteImport } from './routes/_auth/change-password'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as MainEventsIndexRouteImport } from './routes/_main/events/index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminRolesIndexRouteImport } from './routes/_admin/roles/index'
import { Route as AdminPermissionsIndexRouteImport } from './routes/_admin/permissions/index'
import { Route as MainEventsTicketsRouteImport } from './routes/_main/events/tickets'
import { Route as MainEventsEventIdIndexRouteImport } from './routes/_main/events/$eventId/index'
import { Route as AdminUsersProfileIndexRouteImport } from './routes/_admin/users/profile/index'
import { Route as AdminOrganizerEventsIndexRouteImport } from './routes/_admin/organizer/events/index'
import { Route as AdminRolesRoleIdPermissionsRouteImport } from './routes/_admin/roles/$roleId/permissions'
import { Route as AdminOrganizerEventsNewRouteImport } from './routes/_admin/organizer/events/new'
import { Route as AdminOrganizerEventsEventIdIndexRouteImport } from './routes/_admin/organizer/events/$eventId/index'
import { Route as AdminOrganizerEventsEventIdEditRouteImport } from './routes/_admin/organizer/events/$eventId/edit'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const MainEventsIndexRoute = MainEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => MainRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsIndexRoute = AdminPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AdminRoute,
} as any)
const MainEventsTicketsRoute = MainEventsTicketsRouteImport.update({
  id: '/events/tickets',
  path: '/events/tickets',
  getParentRoute: () => MainRoute,
} as any)
const MainEventsEventIdIndexRoute = MainEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => MainRoute,
} as any)
const AdminUsersProfileIndexRoute = AdminUsersProfileIndexRouteImport.update({
  id: '/users/profile/',
  path: '/users/profile/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizerEventsIndexRoute =
  AdminOrganizerEventsIndexRouteImport.update({
    id: '/organizer/events/',
    path: '/organizer/events/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRolesRoleIdPermissionsRoute =
  AdminRolesRoleIdPermissionsRouteImport.update({
    id: '/roles/$roleId/permissions',
    path: '/roles/$roleId/permissions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizerEventsNewRoute = AdminOrganizerEventsNewRouteImport.update({
  id: '/organizer/events/new',
  path: '/organizer/events/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizerEventsEventIdIndexRoute =
  AdminOrganizerEventsEventIdIndexRouteImport.update({
    id: '/organizer/events/$eventId/',
    path: '/organizer/events/$eventId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizerEventsEventIdEditRoute =
  AdminOrganizerEventsEventIdEditRouteImport.update({
    id: '/organizer/events/$eventId/edit',
    path: '/organizer/events/$eventId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AdminDashboardRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/events/tickets': typeof MainEventsTicketsRoute
  '/permissions/': typeof AdminPermissionsIndexRoute
  '/roles/': typeof AdminRolesIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/events/': typeof MainEventsIndexRoute
  '/organizer/events/new': typeof AdminOrganizerEventsNewRoute
  '/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
  '/organizer/events/': typeof AdminOrganizerEventsIndexRoute
  '/users/profile/': typeof AdminUsersProfileIndexRoute
  '/events/$eventId/': typeof MainEventsEventIdIndexRoute
  '/organizer/events/$eventId/edit': typeof AdminOrganizerEventsEventIdEditRoute
  '/organizer/events/$eventId/': typeof AdminOrganizerEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AdminDashboardRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/events/tickets': typeof MainEventsTicketsRoute
  '/permissions': typeof AdminPermissionsIndexRoute
  '/roles': typeof AdminRolesIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/events': typeof MainEventsIndexRoute
  '/organizer/events/new': typeof AdminOrganizerEventsNewRoute
  '/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
  '/organizer/events': typeof AdminOrganizerEventsIndexRoute
  '/users/profile': typeof AdminUsersProfileIndexRoute
  '/events/$eventId': typeof MainEventsEventIdIndexRoute
  '/organizer/events/$eventId/edit': typeof AdminOrganizerEventsEventIdEditRoute
  '/organizer/events/$eventId': typeof AdminOrganizerEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_main/events/tickets': typeof MainEventsTicketsRoute
  '/_admin/permissions/': typeof AdminPermissionsIndexRoute
  '/_admin/roles/': typeof AdminRolesIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_main/events/': typeof MainEventsIndexRoute
  '/_admin/organizer/events/new': typeof AdminOrganizerEventsNewRoute
  '/_admin/roles/$roleId/permissions': typeof AdminRolesRoleIdPermissionsRoute
  '/_admin/organizer/events/': typeof AdminOrganizerEventsIndexRoute
  '/_admin/users/profile/': typeof AdminUsersProfileIndexRoute
  '/_main/events/$eventId/': typeof MainEventsEventIdIndexRoute
  '/_admin/organizer/events/$eventId/edit': typeof AdminOrganizerEventsEventIdEditRoute
  '/_admin/organizer/events/$eventId/': typeof AdminOrganizerEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard'
    | '/change-password'
    | '/events/tickets'
    | '/permissions/'
    | '/roles/'
    | '/users/'
    | '/events/'
    | '/organizer/events/new'
    | '/roles/$roleId/permissions'
    | '/organizer/events/'
    | '/users/profile/'
    | '/events/$eventId/'
    | '/organizer/events/$eventId/edit'
    | '/organizer/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/dashboard'
    | '/change-password'
    | '/events/tickets'
    | '/permissions'
    | '/roles'
    | '/users'
    | '/events'
    | '/organizer/events/new'
    | '/roles/$roleId/permissions'
    | '/organizer/events'
    | '/users/profile'
    | '/events/$eventId'
    | '/organizer/events/$eventId/edit'
    | '/organizer/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_main'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/_admin/dashboard'
    | '/_auth/change-password'
    | '/_main/events/tickets'
    | '/_admin/permissions/'
    | '/_admin/roles/'
    | '/_admin/users/'
    | '/_main/events/'
    | '/_admin/organizer/events/new'
    | '/_admin/roles/$roleId/permissions'
    | '/_admin/organizer/events/'
    | '/_admin/users/profile/'
    | '/_main/events/$eventId/'
    | '/_admin/organizer/events/$eventId/edit'
    | '/_admin/organizer/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/events/': {
      id: '/_main/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof MainEventsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/': {
      id: '/_admin/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/permissions/': {
      id: '/_admin/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AdminPermissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_main/events/tickets': {
      id: '/_main/events/tickets'
      path: '/events/tickets'
      fullPath: '/events/tickets'
      preLoaderRoute: typeof MainEventsTicketsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/events/$eventId/': {
      id: '/_main/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof MainEventsEventIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_admin/users/profile/': {
      id: '/_admin/users/profile/'
      path: '/users/profile'
      fullPath: '/users/profile/'
      preLoaderRoute: typeof AdminUsersProfileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizer/events/': {
      id: '/_admin/organizer/events/'
      path: '/organizer/events'
      fullPath: '/organizer/events/'
      preLoaderRoute: typeof AdminOrganizerEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles/$roleId/permissions': {
      id: '/_admin/roles/$roleId/permissions'
      path: '/roles/$roleId/permissions'
      fullPath: '/roles/$roleId/permissions'
      preLoaderRoute: typeof AdminRolesRoleIdPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizer/events/new': {
      id: '/_admin/organizer/events/new'
      path: '/organizer/events/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof AdminOrganizerEventsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizer/events/$eventId/': {
      id: '/_admin/organizer/events/$eventId/'
      path: '/organizer/events/$eventId'
      fullPath: '/organizer/events/$eventId/'
      preLoaderRoute: typeof AdminOrganizerEventsEventIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/organizer/events/$eventId/edit': {
      id: '/_admin/organizer/events/$eventId/edit'
      path: '/organizer/events/$eventId/edit'
      fullPath: '/organizer/events/$eventId/edit'
      preLoaderRoute: typeof AdminOrganizerEventsEventIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPermissionsIndexRoute: typeof AdminPermissionsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminOrganizerEventsNewRoute: typeof AdminOrganizerEventsNewRoute
  AdminRolesRoleIdPermissionsRoute: typeof AdminRolesRoleIdPermissionsRoute
  AdminOrganizerEventsIndexRoute: typeof AdminOrganizerEventsIndexRoute
  AdminUsersProfileIndexRoute: typeof AdminUsersProfileIndexRoute
  AdminOrganizerEventsEventIdEditRoute: typeof AdminOrganizerEventsEventIdEditRoute
  AdminOrganizerEventsEventIdIndexRoute: typeof AdminOrganizerEventsEventIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPermissionsIndexRoute: AdminPermissionsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminOrganizerEventsNewRoute: AdminOrganizerEventsNewRoute,
  AdminRolesRoleIdPermissionsRoute: AdminRolesRoleIdPermissionsRoute,
  AdminOrganizerEventsIndexRoute: AdminOrganizerEventsIndexRoute,
  AdminUsersProfileIndexRoute: AdminUsersProfileIndexRoute,
  AdminOrganizerEventsEventIdEditRoute: AdminOrganizerEventsEventIdEditRoute,
  AdminOrganizerEventsEventIdIndexRoute: AdminOrganizerEventsEventIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainEventsTicketsRoute: typeof MainEventsTicketsRoute
  MainEventsIndexRoute: typeof MainEventsIndexRoute
  MainEventsEventIdIndexRoute: typeof MainEventsEventIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainEventsTicketsRoute: MainEventsTicketsRoute,
  MainEventsIndexRoute: MainEventsIndexRoute,
  MainEventsEventIdIndexRoute: MainEventsEventIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
